<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Game;
use Carbon\Carbon;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $omori=Game::create(['title'=>'Omori','description'=>'Explore a strange world full of colorful friends and foes. When the time comes, the path you’ve chosen will determine your fate... and perhaps the fate of others as well.','image'=>'img/omori.png','fecha_salida'=>Carbon::parse('2020-12-25'),'genero'=>'RPG']);
        $ultrakill=Game::create(['title'=>'Ultrakill','description'=>'A fast-paced ultraviolent retro FPS combining the skill-based style scoring from character action games with unadulterated carnage inspired by the best shooters of the 90s. Rip apart your foes with varied destructive weapons and shower in their blood to regain your health','image'=>'img/ultrakill.png','fecha_salida'=>Carbon::parse('2020-09-03'),'genero'=>'Shooter']);
        $slime_rancher=Game::create(['title'=>'Slime Rancher','description'=>'Slime Rancher is the tale of Beatrix LeBeau, a plucky, young rancher who sets out for a life a thousand light years away from Earth on the Far, Far Range where she tries her hand at making a living wrangling slimes.','image'=>'img/slime.png','fecha_salida'=>Carbon::parse('2017-08-01'),'genero'=>'Aventura']);
        $shin_megami_tensei_iii_nocturne_hd_remaster=Game::create(['title'=>'Shin Megami Tensei III Nocturne HD Remaster','description'=>'What begins as a normal day in Tokyo turns out to be everything but, when the Conception (an ethereal apocalypse) is invoked. The remains of the world are swallowed by chaos, as a demonic revolution descends into a broken city. Caught between a battle of Gods and demons, the choices you make can bring life, rebirth, or death, and determine who triumphs.','image'=>'img/smt.png','fecha_salida'=>Carbon::parse('2021-05-21'),'genero'=>'RPG']);
        $sekiro_shadows_die_twice=Game::create(['title'=>'Sekiro: Shadows Die Twice','description'=>'Explore late 1500s Sengoku Japan, a brutal period of constant life and death conflict, as you come face to face with larger than life foes in a dark and twisted world. Unleash an arsenal of deadly prosthetic tools and powerful ninja abilities while you blend stealth, vertical traversal, and visceral head to head combat in a bloody confrontation.','image'=>'img/sekiro.png','fecha_salida'=>Carbon::parse('2021-03-21'),'genero'=>'Acción']);
        $nierautomata=Game::create(['title'=>'NieR:Automata','description'=>'NieR: Automata tells the story of androids 2B, 9S and A2 and their battle to reclaim the machine-driven dystopia overrun by powerful machines.Humanity has been driven from the Earth by mechanical beings from another world. In a final effort to take back the planet, the human resistance sends a force of android soldiers to destroy the invaders. Now, a war between machines and androids rages on... A war that could soon unveil a long-forgotten truth of the world.','image'=>'img/nier.png','fecha_salida'=>Carbon::parse('2017-03-17'),'genero'=>'Acción']);
        $nier_replicant_ver122474487139=Game::create(['title'=>'NieR Replicant ver.1.22474487139','description'=>'The upgraded prequel of NieR:Automata. A kind young man sets out with Grimoire Weiss, a strange talking book, to search for the "Sealed verses" in order to save his sister Yonah, who fell terminally ill to the Black Scrawl.','image'=>'img/nierrep.png','fecha_salida'=>Carbon::parse('2021-04-23'),'genero'=>'Acción']);
        $mirrors_edge_catalyst=Game::create(['title'=>'Mirrors Edge Catalyst','description'=>'Mirrors Edge Catalyst raises the action-adventure bar through fluid, first person action and immerses players in Faiths story as she fights for freedom.','image'=>'img/mirrorsedge.png','fecha_salida'=>Carbon::parse('2016-06-07'),'genero'=>'Aventura']);
        $hollow_knight=Game::create(['title'=>'Hollow Knight','description'=>'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.','image'=>'img/hollow.png','fecha_salida'=>Carbon::parse('2017-02-24'),'genero'=>'Platformer']);
        $eastward=Game::create(['title'=>'Eastward','description'=>'Welcome to the charming world of Eastward - population declining! Journey through a society on the brink of collapse. Discover delightful towns, strange creatures and even stranger people! Wield a trusty frying pan and mystic powers on an adventure into the unknown…','image'=>'img/eastward.png','fecha_salida'=>Carbon::parse('2021-09-16'),'genero'=>'RPG']);
        $tower_unite=Game::create(['title'=>'Tower Unite','description'=>'PLAY, CREATE, PARTY! Tower Unite is a community-based virtual world party game with online games, entertainment, activities, and absolutely NO microtransactions.','image'=>'img/towerunite.png','fecha_salida'=>Carbon::parse('2016-04-08'),'genero'=>'MMO']);
        $terraria=Game::create(['title'=>'Terraria','description'=>'Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!','image'=>'img/terraria.png','fecha_salida'=>Carbon::parse('2011-05-16'),'genero'=>'Aventura']);
        $spyro_reignited_trilogy=Game::create(['title'=>'Spyro Reignited Trilogy','description'=>'Explore the expansive realms, re-encounter the fiery personalities and relive the adventure in fully remastered glory. Because when there’s a realm that needs saving, there’s only one dragon to call.','image'=>'img/spyro.png','fecha_salida'=>Carbon::parse('2019-09-03'),'genero'=>'Aventura']);
        $rust=Game::create(['title'=>'Rust','description'=>'The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.','image'=>'img/rust.png','fecha_salida'=>Carbon::parse('2018-02-08'),'genero'=>'PVP']);
        $portal_2=Game::create(['title'=>'Portal 2','description'=>'The game’s two-player cooperative mode features its own entirely separate campaign with a unique story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew about portals. Success will require them to not just act cooperatively, but to think cooperatively.','image'=>'img/portal.png','fecha_salida'=>Carbon::parse('2011-04-19'),'genero'=>'Aventura']);
        $monster_hunter_world=Game::create(['title'=>'Monster Hunter: World','description'=>'As a hunter, youll take on quests to hunt monsters in a variety of habitats.Take down these monsters and receive materials that you can use to create stronger weapons and armor in order to hunt even more dangerous monsters.','image'=>'img/mh.png','fecha_salida'=>Carbon::parse('2018-08-09'),'genero'=>'Acción']);
        $beat_saber=Game::create(['title'=>'Beat Saber','description'=>'Beat Saber is a VR rhythm game where you slash the beats of adrenaline-pumping music as they fly towards you, surrounded by a futuristic world.','image'=>'img/beatsaber.png','fecha_salida'=>Carbon::parse('2019-05-21'),'genero'=>'Ritmo']);
        $gris=Game::create(['title'=>'Gris','description'=>'GRIS is a serene and evocative experience, free of danger, frustration or death. Players will explore a meticulously designed world brought to life with delicate art, detailed animation, and an elegant original score. Through the game light puzzles, platforming sequences, and optional skill-based challenges will reveal themselves as more of Gris’s world becomes accessible.','image'=>'img/gris.png','fecha_salida'=>Carbon::parse('2018-12-13'),'genero'=>'Aventura']);
        $grand_theft_auto_v=Game::create(['title'=>'Grand Theft Auto V','description'=>'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.','image'=>'img/gta.png','fecha_salida'=>Carbon::parse('2015-04-14'),'genero'=>'Aventura']);
        $phasmophobia=Game::create(['title'=>'Phasmophobia','description'=>'Phasmophobia is a 4-player, online co-op, psychological horror game. You and your team of paranormal investigators will enter haunted locations filled with paranormal activity and try to gather as much evidence as you can. Use your ghost-hunting equipment to find and record evidence to sell on to a ghost removal team.','image'=>'img/phasmo.png','fecha_salida'=>Carbon::parse('2020-09-18'),'genero'=>'Horror']);
        $va11_halla=Game::create(['title'=>'VA-11 HALL-A','description'=>'You are a bartender at VA-11 HALL-A, affectionately nicknamed "Valhalla." Although it is just a small bar downtown, it attracts the most fascinating people this side of dystopia. Keep your clients lubricated and you will be made privy to the most interesting stories.','image'=>'img/vallhalla.png','fecha_salida'=>Carbon::parse('2016-06-21'),'genero'=>'RPG']);
        $garrys_mod=Game::create(['title'=>'Garrys Mod','description'=>'You spawn objects and weld them together to create your own contraptions - whether thats a car, a rocket, a catapult or something that doesnt have a name yet - thats up to you. You can do it offline, or join the thousands of players who play online each day.','image'=>'img/garrys.png','fecha_salida'=>Carbon::parse('2006-11-26'),'genero'=>'Sandbox']);
        $kid_a_mnesia_exhibition=Game::create(['title'=>'Kid A Mnesia Exhibition','description'=>'Kid A Mnesia Exhibition is an exploration game based on the music and artwork of the Radiohead albums Kid A (2000) and Amnesiac (2001). Players move through a virtual museum, examining artwork and listening to music and sounds from the albums.','image'=>'img/radiohead.png','fecha_salida'=>Carbon::parse('2021-11-18'),'genero'=>'Aventura']);
        $starbound=Game::create(['title'=>'Starbound','description'=>'You’ve fled your home, only to find yourself lost in space with a damaged ship. Your only option is to beam down to the planet below, repair your ship and set off to explore the universe...','image'=>'img/starbound.png','fecha_salida'=>Carbon::parse('2016-07-22'),'genero'=>'RPG']);
        $superhot=Game::create(['title'=>'Superhot','description'=>'SUPERHOT is the smash-hit FPS where time moves only when you move. No regenerating health bars. No conveniently placed ammo drops. Its you, alone, outnumbered and outgunned. Snatch weapons from fallen enemies to shoot, slice and dodge through a truly cinematic hurricane of slow-motion bullets.','image'=>'img/superhot.png','fecha_salida'=>Carbon::parse('2016-02-25'),'genero'=>'Acción']);
        $trove=Game::create(['title'=>'Trove','description'=>'Grab your friends, hone your blades, and set off for adventure in Trove, the ultimate action MMO! Battle the forces of Shadow in realms filled with incredible dungeons and items created by your fellow players. Whether hunting treasure in far-off lands or building realms of your own, it’s never been this good to be square!','image'=>'img/trove.png','fecha_salida'=>Carbon::parse('2015-07-10'),'genero'=>'MMO']);
        $the_binding_of_isaac_rebirth=Game::create(['title'=>'The Binding of Isaac: Rebirth','description'=>'The Binding of Isaac is a randomly generated action RPG shooter with heavy Rogue-like elements. Following Isaac on his journey players will find bizarre treasures that change Isaac’s form giving him super human abilities and enabling him to fight off droves of mysterious creatures, discover secrets and fight his way to safety.','image'=>'img/isaac.png','fecha_salida'=>Carbon::parse('2014-11-04'),'genero'=>'Roguelike']);
        $celeste=Game::create(['title'=>'Celeste','description'=>'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain.','image'=>'img/celeste.png','fecha_salida'=>Carbon::parse('2018-01-25'),'genero'=>'Platformer']);
        $hogwarts_legacy=Game::create(['title'=>'Hogwarts Legacy','description'=>'Hogwarts Legacy is an open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover magical beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be.','image'=>'img/hogwarts.png','fecha_salida'=>Carbon::parse('2023-02-10'),'genero'=>'RPG']);
        $milk_inside_a_bag_of_milk_inside_a_bag_of_milk=Game::create(['title'=>'Milk inside a bag of milk inside a bag of milk','description'=>'A short story about what sort of challenges everyday little things can be. Help the girl buy milk, be the first not to disappoint her.','image'=>'img/milk.png','fecha_salida'=>Carbon::parse('2020-08-26'),'genero'=>'Aventura']);
        $umineko_when_they_cry_question_arcs=Game::create(['title'=>'Umineko When They Cry - Question Arcs','description'=>'Welcome to the Rokkenjima of October 4, 1986.You have been given a chance to catch a glimpse of the family conference held annually by the Ushiromiya family.The remaining life in the old family headwho has built up a vast fortune is very slim. Everyone desires all that money, no one relents, and no one believes.Who will gain the old heads vast inheritance?Where is the 10 tons of gold that the old head is said to have hidden?','image'=>'img/umineko.png','fecha_salida'=>Carbon::parse('2016-07-08'),'genero'=>'Visual Novel']);
        $detroit_become_human=Game::create(['title'=>'Detroit: Become Human','description'=>'Detroit: Become Human puts the destiny of both mankind and androids in your hands, taking you to a near future where machines have become more intelligent than humans. Every choice you make affects the outcome of the game, with one of the most intricately branching narratives ever created.','image'=>'img/detroit.png','fecha_salida'=>Carbon::parse('2020-06-18'),'genero'=>'Choices Matter']);
        $cyberpunk_2077=Game::create(['title'=>'Cyberpunk 2077','description'=>'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades. The relationships you forge and the choices you make will shape the story and the world around you. Legends are made here. What will yours be?','image'=>'img/cyberpunk.png','fecha_salida'=>Carbon::parse('2020-12-10'),'genero'=>'Open World']);
        $far_cry_5=Game::create(['title'=>'Far Cry 5','description'=>'Far Cry comes to America in the latest installment of the award-winning franchise.Welcome to Hope County, Montana, land of the free and the brave but also home to a fanatical doomsday cult known as Eden’s Gate. Stand up to cult leader Joseph Seed, and his siblings, the Heralds, to spark the fires of resistance and liberate the besieged community.','image'=>'img/farcry.png','fecha_salida'=>Carbon::parse('2018-03-27'),'genero'=>'Open World']);
        $sea_of_thieves=Game::create(['title'=>'Sea of Thieves','description'=>'Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting – everything you need to live the pirate life and become a legend in your own right. With no set roles, you have complete freedom to approach the world, and other players, however you choose.','image'=>'img/seaofthieves.png','fecha_salida'=>Carbon::parse('2020-06-03'),'genero'=>'Aventura']);
        $destiny_2=Game::create(['title'=>'Destiny 2','description'=>'Dive into the world of Destiny 2 to explore the mysteries of the solar system and experience responsive first-person shooter combat. Unlock powerful elemental abilities and collect unique gear to customize your Guardians look and playstyle. Enjoy Destiny 2’s cinematic story, challenging co-op missions, and a variety of PvP modes alone or with friends.','image'=>'img/destiny.png','fecha_salida'=>Carbon::parse('2019-10-01'),'genero'=>'Shooter']);
        $dayz=Game::create(['title'=>'DayZ','description'=>'How long can you survive a post-apocalyptic world? A land overrun with an infected "zombie" population, where you compete with other survivors for limited resources. Will you team up with strangers and stay strong together? Or play as a lone wolf to avoid betrayal? This is DayZ – this is your story.','image'=>'img/dayz.png','fecha_salida'=>Carbon::parse('2018-12-13'),'genero'=>'Survival']);
        $minecraft=Game::create(['title'=>'Minecraft','description'=>'Minecraft is a 3D sandbox game developed by Mojang Studios where players interact with a fully modifiable three-dimensional environment made of blocks and entities. Its diverse gameplay lets players choose the way they play, allowing for countless possibilities.','image'=>'img/minecraft.png','fecha_salida'=>Carbon::parse('2011-11-18'),'genero'=>'Sandbox']);
        $everhood=Game::create(['title'=>'Everhood','description'=>'An UNCONVENTIONAL ADVENTURE RPG that takes place in an inexpressible world filled with amusing musical battles and strange delightful encounters. To put it simply: You are in for a ride.','image'=>'img/everhood.png','fecha_salida'=>Carbon::parse('2021-03-04'),'genero'=>'RPG']);
        $silent_hill_2=Game::create(['title'=>'Silent Hill 2','description'=>'James Sunderland has arrived in the town of Silent Hill, Maine, after receiving a letter from his wife Mary, despite the fact that she suffered a chronic disease and died three years prior. The letter claims that Mary is waiting for James in their "special place", which confuses James, as the whole town of Silent Hill was their "special place".','image'=>'img/silenthill2.png','fecha_salida'=>Carbon::parse('2001-09-24'),'genero'=>'Horror']);
        $eastern_mind_the_lost_souls_of_tong_nou=Game::create(['title'=>'Eastern Mind: The Lost Souls of Tong Nou','description'=>'Eastern Mind is a point-and-click adventure game about a man named Rin who has lost his soul. A friend gives him an artificial soul that will last 49 days, with which he goes on a quest to a location known as Tong Nou, to die and be reincarnated nine times, in order to recover his soul. Transmigration is a core game mechanic, requiring the player to die and be reborn as part of the experience, before he can finally ascend to the center of the island.','image'=>'img/easternmind.png','fecha_salida'=>Carbon::parse('1994-04-01'),'genero'=>'Point & Click']);
        $osu=Game::create(['title'=>'osu!','description'=>'Game levels are called beatmaps. In each beatmap, a song will play and different Beats hit elements (hit circles, sliders and spinners) will appear on the play field. Players must use a pointing device to manipulate these elements in time with the playing songs rhythm in order to earn points. The use of a graphics tablet in combination with a keyboard is common in osu!, although some players do use a mouse.','image'=>'img/osu.png','fecha_salida'=>Carbon::parse('2007-09-16'),'genero'=>'Ritmo']);
        $outer_wilds=Game::create(['title'=>'Outer Wilds','description'=>'Outer Wilds features an unnamed player character exploring a solar system that is stuck in a time loop, going back 22 minutes before its star goes supernova. Thus, the player is encouraged to learn why by exploring and uncovering secrets of an extinct race known as the Nomai, who previously colonized the solar system hundreds of thousands of years ago. In the first part of the game, the player links with an ancient Nomai statue which ensures that the player retains information discovered in each time loop when it restarts.','image'=>'img/outerwilds.png','fecha_salida'=>Carbon::parse('2019-05-28'),'genero'=>'Aventura']);
        $half_life_alyx=Game::create(['title'=>'Half-Life: Alyx','description'=>'Half-Life: Alyx is Valve’s VR return to the Half-Life series. It’s the story of an impossible fight against a vicious alien race known as the Combine, set between the events of Half-Life and Half-Life 2. Playing as Alyx Vance, you are humanity’s only chance for survival.','image'=>'img/halflifealyx.png','fecha_salida'=>Carbon::parse('2020-03-23'),'genero'=>'Aventura']);
        $dead_space=Game::create(['title'=>'Dead Space','description'=>'Isaac Clarke is an everyman engineer on a mission to repair a vast mining ship, the USG Ishimura, only to discover something has gone horribly wrong. The ships crew has been slaughtered and Isaac’s beloved partner, Nicole, is lost somewhere on board.Now alone and armed with only his engineering tools and skills, Isaac races to find Nicole as the nightmarish mystery of what happened aboard the Ishimura unravels around him. Trapped with hostile creatures called Necromorphs, Isaac faces a battle for survival, not only against the escalating terrors of the ship but against his own crumbling sanity.','image'=>'img/deadspace.png','fecha_salida'=>Carbon::parse('2023-01-27'),'genero'=>'Horror']);
        $the_last_of_us_parte_i=Game::create(['title'=>'The Last of Us Parte I','description'=>'In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey.','image'=>'img/tlou1.png','fecha_salida'=>Carbon::parse('2013-06-13'),'genero'=>'Aventura']);
        $the_last_of_us_parte_ii=Game::create(['title'=>'The Last of Us Parte II','description'=>'Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming. Living amongst a thriving community of survivors has allowed them peace and stability, despite the constant threat of the infected and other, more desperate survivors. When a violent event disrupts that peace, Ellie embarks on a relentless journey to carry out justice and find closure. As she hunts those responsible one by one, she is confronted with the devastating physical and emotional repercussions of her actions.','image'=>'img/tlou2.png','fecha_salida'=>Carbon::parse('2020-06-19'),'genero'=>'Aventura']);
        $ghostrunner=Game::create(['title'=>'Ghostrunner','description'=>'Ghostrunner is a hardcore FPP slasher packed with lightning-fast action, set in a grim, cyberpunk megastructure. Climb Dharma Tower, humanitys last shelter, after a world-ending cataclysm. Make your way up from the bottom to the top, confront the tyrannical Keymaster, and take your revenge.','image'=>'img/ghostrunner.png','fecha_salida'=>Carbon::parse('2020-10-27'),'genero'=>'Acción']);
        $portal=Game::create(['title'=>'Portal','description'=>'Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and will offer gamers hours of unique gameplay. Players must solve physical puzzles and challenges by opening portals to maneuvering objects, and themselves, through space.','image'=>'img/portal1.png','fecha_salida'=>Carbon::parse('2007-10-07'),'genero'=>'Aventura']);
        $it_takes_two=Game::create(['title'=>'It takes two','description'=>'Embark on the craziest journey of your life in It Takes Two, a genre-bending platform adventure created purely for co-op. Invite a friend to join for free with Friend’s Pass and work together across a huge variety of gleefully disruptive gameplay challenges. Play as the clashing couple Cody and May, two humans turned into dolls by a magic spell. Together, trapped in a fantastical world where the unpredictable hides around every corner, they are reluctantly challenged with saving their fractured relationship.','image'=>'img/takestwo.png','fecha_salida'=>Carbon::parse('2021-03-26'),'genero'=>'Cooperativo']);
        $unravel_two=Game::create(['title'=>'Unravel two','description'=>'When you cut ties to the past, new bonds form. In Unravel Two, create a Yarny of your very own. Then build relationships with other Yarnys in local co-op or as a single player, fostering friendship and support as you journey together. Begin your adventure in a cold and imposing land, then watch your surroundings blossom with new life as you chase the spark of adventure. Dive into an immersive story filled with energy, exuberance, inspiration, even monsters. Approach every challenge with positivity and fearlessness to awaken the world around you, and discover an unbreakable bond between friends.','image'=>'img/unraveltwo.png','fecha_salida'=>Carbon::parse('2018-06-09'),'genero'=>'Aventura']);
        $undertale=Game::create(['title'=>'Undertale','description'=>'In this RPG, you control a human who falls underground into the world of monsters. Now you must find your way out... or stay trapped forever.','image'=>'img/undertale.png','fecha_salida'=>Carbon::parse('2015-09-15'),'genero'=>'RPG']);
        $papers_please=Game::create(['title'=>'Papers, Please','description'=>'The communist state of Arstotzka has just ended a 6-year war with neighboring Kolechia and reclaimed its rightful half of the border town, Grestin. Your job as immigration inspector is to control the flow of people entering the Arstotzkan side of Grestin from Kolechia. Among the throngs of immigrants and visitors looking for work are hidden smugglers, spies, and terrorists. Using only the documents provided by travelers and the Ministry of Admissions primitive inspect, search, and fingerprint systems you must decide who can enter Arstotzka and who will be turned away or arrested.','image'=>'img/papersplease.png','fecha_salida'=>Carbon::parse('2013-08-08'),'genero'=>'Aventura']);
        $stray=Game::create(['title'=>'Stray','description'=>'Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city. Stray is a third-person cat adventure game set amidst the detailed, neon-lit alleys of a decaying cybercity and the murky environments of its seedy underbelly. Roam surroundings high and low, defend against unforeseen threats and solve the mysteries of this unwelcoming place inhabited by curious droids and dangerous creatures.','image'=>'img/stray.png','fecha_salida'=>Carbon::parse('2022-07-19'),'genero'=>'Aventura']);
        $shadow_of_the_colossus=Game::create(['title'=>'Shadow of the colossus','description'=>'It takes place in a fantasy setting and follows Wander, a young man who enters an isolated and abandoned region of the realm seeking the power to revive a girl named Mono. The player assumes the role of Wander as he embarks on a mission that might entail Monos resurrection: to locate and destroy the colossi, sixteen massive beings spread across the forbidden land, which the protagonist traverses by horseback and on foot.','image'=>'img/colossus.png','fecha_salida'=>Carbon::parse('2005-10-18'),'genero'=>'Acción']);
        $red_dead_redemption_2=Game::create(['title'=>'Red Dead Redemption 2','description'=>'Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him.','image'=>'img/rdr2.png','fecha_salida'=>Carbon::parse('2019-12-05'),'genero'=>'Mundo Abierto']);
        $cities_skylines=Game::create(['title'=>'Cities: Skylines','description'=>'Cities: Skylines is a modern take on the classic city simulation. The game introduces new game play elements to realize the thrill and hardships of creating and maintaining a real city whilst expanding on some well-established tropes of the city building experience.','image'=>'img/citiesskylines.png','fecha_salida'=>Carbon::parse('2015-03-10'),'genero'=>'Simulación']);
    }
}
