<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Game;
use Carbon\Carbon;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $omori=Game::create(['title'=>'Omori','description'=>'Explore a strange world full of colorful friends and foes. When the time comes, the path you’ve chosen will determine your fate... and perhaps the fate of others as well.','image'=>'img/omori.png','fecha_salida'=>Carbon::parse('2020-12-25'),'genero'=>'RPG']);
        $ultrakill=Game::create(['title'=>'Ultrakill','description'=>'A fast-paced ultraviolent retro FPS combining the skill-based style scoring from character action games with unadulterated carnage inspired by the best shooters of the 90s. Rip apart your foes with varied destructive weapons and shower in their blood to regain your health','image'=>'img/ultrakill.png','fecha_salida'=>Carbon::parse('2020-09-03'),'genero'=>'Shooter']);
        $slime_rancher=Game::create(['title'=>'Slime Rancher','description'=>'Slime Rancher is the tale of Beatrix LeBeau, a plucky, young rancher who sets out for a life a thousand light years away from Earth on the Far, Far Range where she tries her hand at making a living wrangling slimes.','image'=>'img/slime.png','fecha_salida'=>Carbon::parse('2017-08-01'),'genero'=>'Aventura']);
        $shin_megami_tensei_iii_nocturne_hd_remaster=Game::create(['title'=>'Shin Megami Tensei III Nocturne HD Remaster','description'=>'What begins as a normal day in Tokyo turns out to be everything but, when the Conception (an ethereal apocalypse) is invoked. The remains of the world are swallowed by chaos, as a demonic revolution descends into a broken city. Caught between a battle of Gods and demons, the choices you make can bring life, rebirth, or death, and determine who triumphs.','image'=>'img/smt.png','fecha_salida'=>Carbon::parse('2021-05-21'),'genero'=>'RPG']);
        $sekiro_shadows_die_twice=Game::create(['title'=>'Sekiro: Shadows Die Twice','description'=>'Explore late 1500s Sengoku Japan, a brutal period of constant life and death conflict, as you come face to face with larger than life foes in a dark and twisted world. Unleash an arsenal of deadly prosthetic tools and powerful ninja abilities while you blend stealth, vertical traversal, and visceral head to head combat in a bloody confrontation.','image'=>'img/sekiro.png','fecha_salida'=>Carbon::parse('2021-03-21'),'genero'=>'Acción']);
        $nierautomata=Game::create(['title'=>'NieR:Automata','description'=>'NieR: Automata tells the story of androids 2B, 9S and A2 and their battle to reclaim the machine-driven dystopia overrun by powerful machines.Humanity has been driven from the Earth by mechanical beings from another world. In a final effort to take back the planet, the human resistance sends a force of android soldiers to destroy the invaders. Now, a war between machines and androids rages on... A war that could soon unveil a long-forgotten truth of the world.','image'=>'img/nier.png','fecha_salida'=>Carbon::parse('2017-03-17'),'genero'=>'Acción']);
        $nier_replicant_ver122474487139=Game::create(['title'=>'NieR Replicant ver.1.22474487139','description'=>'The upgraded prequel of NieR:Automata. A kind young man sets out with Grimoire Weiss, a strange talking book, to search for the "Sealed verses" in order to save his sister Yonah, who fell terminally ill to the Black Scrawl.','image'=>'img/nierrep.png','fecha_salida'=>Carbon::parse('2021-04-23'),'genero'=>'Acción']);
        $mirrors_edge_catalyst=Game::create(['title'=>'Mirrors Edge Catalyst','description'=>'Mirrors Edge Catalyst raises the action-adventure bar through fluid, first person action and immerses players in Faiths story as she fights for freedom.','image'=>'img/mirrorsedge.png','fecha_salida'=>Carbon::parse('2016-06-07'),'genero'=>'Aventura']);
        $hollow_knight=Game::create(['title'=>'Hollow Knight','description'=>'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.','image'=>'img/hollow.png','fecha_salida'=>Carbon::parse('2017-02-24'),'genero'=>'Platformer']);
        $eastward=Game::create(['title'=>'Eastward','description'=>'Welcome to the charming world of Eastward - population declining! Journey through a society on the brink of collapse. Discover delightful towns, strange creatures and even stranger people! Wield a trusty frying pan and mystic powers on an adventure into the unknown…','image'=>'img/eastward.png','fecha_salida'=>Carbon::parse('2021-09-16'),'genero'=>'RPG']);
        $tower_unite=Game::create(['title'=>'Tower Unite','description'=>'PLAY, CREATE, PARTY! Tower Unite is a community-based virtual world party game with online games, entertainment, activities, and absolutely NO microtransactions.','image'=>'img/towerunite.png','fecha_salida'=>Carbon::parse('2016-04-08'),'genero'=>'MMO']);
        $terraria=Game::create(['title'=>'Terraria','description'=>'Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!','image'=>'img/terraria.png','fecha_salida'=>Carbon::parse('2011-05-16'),'genero'=>'Aventura']);
        $spyro_reignited_trilogy=Game::create(['title'=>'Spyro Reignited Trilogy','description'=>'Explore the expansive realms, re-encounter the fiery personalities and relive the adventure in fully remastered glory. Because when there’s a realm that needs saving, there’s only one dragon to call.','image'=>'img/spyro.png','fecha_salida'=>Carbon::parse('2019-09-03'),'genero'=>'Aventura']);
        $rust=Game::create(['title'=>'Rust','description'=>'The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.','image'=>'img/rust.png','fecha_salida'=>Carbon::parse('2018-02-08'),'genero'=>'PVP']);
        $portal_2=Game::create(['title'=>'Portal 2','description'=>'The game’s two-player cooperative mode features its own entirely separate campaign with a unique story, test chambers, and two new player characters. This new mode forces players to reconsider everything they thought they knew about portals. Success will require them to not just act cooperatively, but to think cooperatively.','image'=>'img/portal.png','fecha_salida'=>Carbon::parse('2011-04-19'),'genero'=>'Aventura']);
        $monster_hunter_world=Game::create(['title'=>'Monster Hunter: World','description'=>'As a hunter, youll take on quests to hunt monsters in a variety of habitats.Take down these monsters and receive materials that you can use to create stronger weapons and armor in order to hunt even more dangerous monsters.','image'=>'img/mh.png','fecha_salida'=>Carbon::parse('2018-08-09'),'genero'=>'Acción']);
        $beat_saber=Game::create(['title'=>'Beat Saber','description'=>'Beat Saber is a VR rhythm game where you slash the beats of adrenaline-pumping music as they fly towards you, surrounded by a futuristic world.','image'=>'img/beatsaber.png','fecha_salida'=>Carbon::parse('2019-05-21'),'genero'=>'Ritmo']);
        $gris=Game::create(['title'=>'Gris','description'=>'GRIS is a serene and evocative experience, free of danger, frustration or death. Players will explore a meticulously designed world brought to life with delicate art, detailed animation, and an elegant original score. Through the game light puzzles, platforming sequences, and optional skill-based challenges will reveal themselves as more of Gris’s world becomes accessible.','image'=>'img/gris.png','fecha_salida'=>Carbon::parse('2018-12-13'),'genero'=>'Aventura']);
        $grand_theft_auto_v=Game::create(['title'=>'Grand Theft Auto V','description'=>'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to survive in a ruthless city in which they can trust nobody, least of all each other.','image'=>'img/gta.png','fecha_salida'=>Carbon::parse('2015-04-14'),'genero'=>'Aventura']);
        $phasmophobia=Game::create(['title'=>'Phasmophobia','description'=>'Phasmophobia is a 4-player, online co-op, psychological horror game. You and your team of paranormal investigators will enter haunted locations filled with paranormal activity and try to gather as much evidence as you can. Use your ghost-hunting equipment to find and record evidence to sell on to a ghost removal team.','image'=>'img/phasmo.png','fecha_salida'=>Carbon::parse('2020-09-18'),'genero'=>'Horror']);
        $va11_halla=Game::create(['title'=>'VA-11 HALL-A','description'=>'You are a bartender at VA-11 HALL-A, affectionately nicknamed "Valhalla." Although it is just a small bar downtown, it attracts the most fascinating people this side of dystopia. Keep your clients lubricated and you will be made privy to the most interesting stories.','image'=>'img/vallhalla.png','fecha_salida'=>Carbon::parse('2016-06-21'),'genero'=>'RPG']);
        $garrys_mod=Game::create(['title'=>'Garrys Mod','description'=>'You spawn objects and weld them together to create your own contraptions - whether thats a car, a rocket, a catapult or something that doesnt have a name yet - thats up to you. You can do it offline, or join the thousands of players who play online each day.','image'=>'img/garrys.png','fecha_salida'=>Carbon::parse('2006-11-26'),'genero'=>'Sandbox']);
        $kid_a_mnesia_exhibition=Game::create(['title'=>'Kid A Mnesia Exhibition','description'=>'Kid A Mnesia Exhibition is an exploration game based on the music and artwork of the Radiohead albums Kid A (2000) and Amnesiac (2001). Players move through a virtual museum, examining artwork and listening to music and sounds from the albums.','image'=>'img/radiohead.png','fecha_salida'=>Carbon::parse('2021-11-18'),'genero'=>'Aventura']);
        $starbound=Game::create(['title'=>'Starbound','description'=>'You’ve fled your home, only to find yourself lost in space with a damaged ship. Your only option is to beam down to the planet below, repair your ship and set off to explore the universe...','image'=>'img/starbound.png','fecha_salida'=>Carbon::parse('2016-07-22'),'genero'=>'RPG']);
        $superhot=Game::create(['title'=>'Superhot','description'=>'SUPERHOT is the smash-hit FPS where time moves only when you move. No regenerating health bars. No conveniently placed ammo drops. Its you, alone, outnumbered and outgunned. Snatch weapons from fallen enemies to shoot, slice and dodge through a truly cinematic hurricane of slow-motion bullets.','image'=>'img/superhot.png','fecha_salida'=>Carbon::parse('2016-02-25'),'genero'=>'Acción']);
        $trove=Game::create(['title'=>'Trove','description'=>'Grab your friends, hone your blades, and set off for adventure in Trove, the ultimate action MMO! Battle the forces of Shadow in realms filled with incredible dungeons and items created by your fellow players. Whether hunting treasure in far-off lands or building realms of your own, it’s never been this good to be square!','image'=>'img/trove.png','fecha_salida'=>Carbon::parse('2015-07-10'),'genero'=>'MMO']);
        $the_binding_of_isaac_rebirth=Game::create(['title'=>'The Binding of Isaac: Rebirth','description'=>'The Binding of Isaac is a randomly generated action RPG shooter with heavy Rogue-like elements. Following Isaac on his journey players will find bizarre treasures that change Isaac’s form giving him super human abilities and enabling him to fight off droves of mysterious creatures, discover secrets and fight his way to safety.','image'=>'img/isaac.png','fecha_salida'=>Carbon::parse('2014-11-04'),'genero'=>'Roguelike']);
        $celeste=Game::create(['title'=>'Celeste','description'=>'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain.','image'=>'img/celeste.png','fecha_salida'=>Carbon::parse('2018-01-25'),'genero'=>'Platformer']);
        $hogwarts_legacy=Game::create(['title'=>'Hogwarts Legacy','description'=>'Hogwarts Legacy is an open-world action RPG set in the world first introduced in the Harry Potter books. Embark on a journey through familiar and new locations as you explore and discover magical beasts, customize your character and craft potions, master spell casting, upgrade talents and become the wizard you want to be.','image'=>'img/hogwarts.png','fecha_salida'=>Carbon::parse('2023-02-10'),'genero'=>'RPG']);
        $milk_inside_a_bag_of_milk_inside_a_bag_of_milk=Game::create(['title'=>'Milk inside a bag of milk inside a bag of milk','description'=>'A short story about what sort of challenges everyday little things can be. Help the girl buy milk, be the first not to disappoint her.','image'=>'img/milk.png','fecha_salida'=>Carbon::parse('2020-08-26'),'genero'=>'Aventura']);
        $umineko_when_they_cry_question_arcs=Game::create(['title'=>'Umineko When They Cry - Question Arcs','description'=>'Welcome to the Rokkenjima of October 4, 1986.You have been given a chance to catch a glimpse of the family conference held annually by the Ushiromiya family.The remaining life in the old family headwho has built up a vast fortune is very slim. Everyone desires all that money, no one relents, and no one believes.Who will gain the old heads vast inheritance?Where is the 10 tons of gold that the old head is said to have hidden?','image'=>'img/umineko.png','fecha_salida'=>Carbon::parse('2016-07-08'),'genero'=>'Visual Novel']);
        $detroit_become_human=Game::create(['title'=>'Detroit: Become Human','description'=>'Detroit: Become Human puts the destiny of both mankind and androids in your hands, taking you to a near future where machines have become more intelligent than humans. Every choice you make affects the outcome of the game, with one of the most intricately branching narratives ever created.','image'=>'img/detroit.png','fecha_salida'=>Carbon::parse('2020-06-18'),'genero'=>'Choices Matter']);
        $cyberpunk_2077=Game::create(['title'=>'Cyberpunk 2077','description'=>'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades. The relationships you forge and the choices you make will shape the story and the world around you. Legends are made here. What will yours be?','image'=>'img/cyberpunk.png','fecha_salida'=>Carbon::parse('2020-12-10'),'genero'=>'Open World']);
        $far_cry_5=Game::create(['title'=>'Far Cry 5','description'=>'Far Cry comes to America in the latest installment of the award-winning franchise.Welcome to Hope County, Montana, land of the free and the brave but also home to a fanatical doomsday cult known as Eden’s Gate. Stand up to cult leader Joseph Seed, and his siblings, the Heralds, to spark the fires of resistance and liberate the besieged community.','image'=>'img/farcry.png','fecha_salida'=>Carbon::parse('2018-03-27'),'genero'=>'Open World']);
        $sea_of_thieves=Game::create(['title'=>'Sea of Thieves','description'=>'Sea of Thieves offers the essential pirate experience, from sailing and fighting to exploring and looting – everything you need to live the pirate life and become a legend in your own right. With no set roles, you have complete freedom to approach the world, and other players, however you choose.','image'=>'img/seaofthieves.png','fecha_salida'=>Carbon::parse('2020-06-03'),'genero'=>'Aventura']);
        $destiny_2=Game::create(['title'=>'Destiny 2','description'=>'Dive into the world of Destiny 2 to explore the mysteries of the solar system and experience responsive first-person shooter combat. Unlock powerful elemental abilities and collect unique gear to customize your Guardians look and playstyle. Enjoy Destiny 2’s cinematic story, challenging co-op missions, and a variety of PvP modes alone or with friends.','image'=>'img/destiny.png','fecha_salida'=>Carbon::parse('2019-10-01'),'genero'=>'Shooter']);
        $dayz=Game::create(['title'=>'DayZ','description'=>'How long can you survive a post-apocalyptic world? A land overrun with an infected "zombie" population, where you compete with other survivors for limited resources. Will you team up with strangers and stay strong together? Or play as a lone wolf to avoid betrayal? This is DayZ – this is your story.','image'=>'img/dayz.png','fecha_salida'=>Carbon::parse('2018-12-13'),'genero'=>'Survival']);
        $minecraft=Game::create(['title'=>'Minecraft','description'=>'Minecraft is a 3D sandbox game developed by Mojang Studios where players interact with a fully modifiable three-dimensional environment made of blocks and entities. Its diverse gameplay lets players choose the way they play, allowing for countless possibilities.','image'=>'img/minecraft.png','fecha_salida'=>Carbon::parse('2011-11-18'),'genero'=>'Sandbox']);
    }
}
